language: cpp

sudo: false

os:
  - linux
  - osx

env:
  global:
    - DISPLAY=":99.0"
    - AUDIODEV="null"
    - XVFB_OPTS=":99.0 -ac -screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset"
  matrix:
    - BITS=64 PYTHON_BACKEND=cpython
    - BITS=64 PYTHON_BACKEND=pypy
    - BITS=32 PYTHON_BACKEND=cpython
    - BITS=32 PYTHON_BACKEND=pypy

matrix:
  allow_failures:
    # TODO: fix x11-32 ! (use docker for the build ?)
    - BITS: 32
  exclude:
    - os: osx
      BITS: 32

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
# Out of order (http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html)
#      - llvm-toolchain-precise
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libasound2-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libxinerama-dev
      - libxrandr-dev
      # Needed to cross-compile x86 on amd64
      - libc6-dev-i386
      - libx32gcc-7-dev
      - gcc-7-multilib
      # Need gcc > 4.6 for -std=c++11 and >= 7 for LTO 6.0 (used by gnative wrapper)
      - gcc-7
      - g++-7
      - python3
      - python3-pip
#      - clang-3.9
      - valgrind

before_install:
  - pyenv shell 3.6.3
  - pip3 install virtualenv --user
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install scons; fi;
# Needed because scons doesn't inherit the customized $PATH env
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; export CC=gcc-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; export TARGET_PLATFORM=x11-$BITS; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; export TARGET_PLATFORM=osx-$BITS; fi
# See https://github.com/pyenv/pyenv/issues/228
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; eval "$(pyenv init -)"; fi
  - python --version
  - $CC --version
  - scons --version

before_script:
# Start X11 server
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $XVFB_OPTS; fi;
  - sleep 3 # give xvfb some time to start


script:
  - set -e  # Enable fail on first error
  - scons platform=$TARGET_PLATFORM backend=$PYTHON_BACKEND CC=$CC release_suffix=$TRAVIS_BRANCH release
# Tests need x11 server with opengl3 or compile godot with platform=server (both not working so far...)
  # - LIBGL_ALWAYS_SOFTWARE=1 scons debugger=valgrind platform=$TARGET_PLATFORM backend=$PYTHON_BACKEND CC=$CC test
  - set +e

deploy:
  provider: releases
  api_key:
    secure: IGucQcPBy6g10GiyLXb25AU4Ie3NwiWJlbgL3maY9gt7hPrYXa9EhmpXqxZMVw5Kv3mShnqlIKb3QcDCS0iuJBD7i++HX32brA3fhlehSea9V5cbp+uZT+bO4ZVdd7lOr9pTNsbN3ny7Dow125EoO4/D897oJc2NSGe1ul5Kgn285H87vC9KdtOxzErk3Jcf/4UO+qFMCtMKfShQa8bHgKGJ/QMvlVtfNWRLzGSp+SMCH6O2mKrCpbPcCajzRc4jH/rZE8AcpoUwMBfvMvT1y0c/1qXsRh5d98aGMgctXTehxv13YNbx6hsOFXU1Kn5xQF+nzHeZQmUQjWO81JflYmrm3yG4nbX9DdoIzg4zHVVXEN69xZPvyyH1dh8G8b3eDag7faFidNA6qmbQ978hRaDWOnwwzWBkEc19Ah6pYIrmwHPO5nq+mmzGIfcfJCIspRe7cv//Ab6eZxJnhK2g20AbIRvcIEL1o1OU+CsBfZcFouD7j2fD8K99HhRNJTIomx9SyHTAvwBTzRUKFNGjAW6TCrRilfV68VS5wRmjVYbpq8RJYQNG/NIjTgx+7H8L9XKb9fe+hYU2vHolUIFgZAvoFqeThJC/EcynBpbiSe6A4x3yadrZ8taLYEXPVYyoJQXlgjGgfSi7j98LdbFWEojNvbyMh2dnHwyz0YXfTK8=
  skip_cleanup: true
  file_glob: true
  file: godot-python-*.zip
  on:
    repo: touilleMan/godot-python
    tags: true
