language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    - LLVM_VERSION=3.8.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
    # Use commit instead of tag as long as 3.0 is not released
    # - GODOT_REPO=https://github.com/godotengine/godot.git
    # - GODOT_TAG=master  # I like to live dangerously ;-)
    - GODOT_REPO=https://github.com/touilleMan/godot.git
    - GODOT_TAG=gdnative_missing_functions
    # Cannot use release given travis's glibc clash with -ffast-math with clang
    # other solution is to set `-D__extern_always_inline="extern __always_inline"`
    - BUILD_EXTRA_OPTS="-j4 target=debug tools=yes module_pythonscript_enabled=yes"
    - TEST_EXTRA_OPTS=""
    - DISPLAY=:99.0
  matrix:
    - GODOT_TARGET=x11
    # nothing else yet...

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
# Out of order (http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html)
#      - llvm-toolchain-precise
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libasound2-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libxinerama-dev
      - libxrandr-dev
      # Need gcc > 4.6 for -std=c++11
      - gcc-5
      - g++-5
#      - clang-3.9
      - python3
      - valgrind

before_install:
  - if [[ "$CXX" == "clang++" ]]; then wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH; fi
  - if [[ "$CXX" == "clang++" ]]; then mkdir $HOME/clang+llvm; fi
  - if [[ "$CXX" == "clang++" ]]; then tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1; fi
  - if [[ "$CXX" == "clang++" ]]; then export PATH=$HOME/clang+llvm/bin:$PATH; fi
  - if [[ "$CXX" == "clang++" ]]; then clang --version; fi

before_script:
  # Cannot use this with commit id
  - git clone -b $GODOT_TAG --single-branch  --recursive --depth 1 $GODOT_REPO
  # - git clone --recursive $GODOT_REPO
# Dunno why but .gitignore is modified by something...
  - git --git-dir=godot/.git reset --hard
  - git --git-dir=godot/.git checkout $GODOT_TAG
  - git --git-dir=godot/.git rev-parse HEAD
  - ln -s `pwd`/pythonscript godot/modules/pythonscript

script:
  - if [[ "$CXX" == "g++" ]]; then make compile OPTS="platform=$GODOT_TARGET $BUILD_EXTRA_OPTS CXX=g++-5 CC=gcc-5"; fi
  - if [[ "$CXX" == "clang++" ]]; then make compile OPTS="platform=$GODOT_TARGET $BUILD_EXTRA_OPTS use_llvm=yes"; fi
  - cp pythonscript/cpython/libpython3.6dm.so.1.0 godot/bin
  - LIBGL_ALWAYS_SOFTWARE=1 make test DEBUG=valgrind EXTRA_OPTS=$TEST_EXTRA_OPTS
